### ISSUE TITLE
卡片移动端显示问题

### ISSUE THREAD

**Issue by xwyzsn** [qianbinbin/dict2anki#21]
hello
想问一下导入到手机的卡片在交互上是有问题吗请问?
![1633707567(1)](https://user-images.githubusercontent.com/55912637/136585075-b7550fc5-34fa-460d-a012-23514c39d1e7.png)
类似与这种的都不能展开。:upside_down_face:

**Comment by qianbinbin** [comment]
是所有卡片都不能展开还是只有这个有问题？
把背面的源码贴出来看看

**Comment by xwyzsn** [comment]
```javascript
//背面模板
{{FrontSide}}
<hr id=answer>
{{背面}}
```
- 在pc端是都可以正常展开的,
- 移动端(手机IOS,和ipad都"**很难展开**",就是为数不多的某些卡片可能展开过一次两次。

**Comment by qianbinbin** [comment]
那个是模板，不是源码，不过问题原因大概知道了
PC 上可以，说明卡片本身没问题，估计是墙的原因。因为卡片用了一些在线的 js，域名是 cdn.ampproject.org，然而我试了一下已经被墙了，翻墙应该就可以了
Edit：并不是一直墙，时好时坏

**Comment by xwyzsn** [comment]
hhh是的,因为电脑上一直挂着梯子,刚刚手机试了一下翻墙能用了!谢谢!!! :slightly_smiling_face:

**Comment by qianbinbin** [comment]
不客气
